#include "main.h"




GPIO_TypeDef *peripherals [208] = {
	// for non-GPIO pins, the peripheral is stored as NULL
	//0
	GPIOE, GPIOE, GPIOE, GPIOE, GPIOE, NULL, GPIOI, GPIOC, GPIOC, GPIOC,
	//10
	GPIOI, GPIOI, GPIOI, NULL, NULL, GPIOF, GPIOF, GPIOF, GPIOI, GPIOI,
	//20
	GPIOI, GPIOF, GPIOF, GPIOF, NULL, NULL, GPIOF, GPIOF, GPIOF, GPIOF,
	//30
	GPIOF, GPIOH, GPIOH, NULL, GPIOC, GPIOC, GPIOC, GPIOC, NULL, NULL,
	//40
	NULL, NULL, GPIOA, GPIOA, GPIOA, GPIOH, GPIOH, GPIOH, GPIOH, GPIOA,
	//50
	NULL, NULL, GPIOA, GPIOA, GPIOA, GPIOA, GPIOC, GPIOC, NULL, NULL,
	//60
	GPIOB, GPIOB, GPIOB, GPIOI, GPIOJ, GPIOJ, GPIOJ, GPIOJ, GPIOJ, GPIOF,
	//70
	GPIOF, NULL, NULL, GPIOF, GPIOF, GPIOF, GPIOG, GPIOG, GPIOE, GPIOE,
	//80
	GPIOE, NULL, NULL, GPIOE, GPIOE, GPIOE, GPIOE, GPIOE, GPIOE, GPIOB,
	//90
	GPIOB, NULL, NULL, NULL, GPIOJ, GPIOH, GPIOH, GPIOH, GPIOH, GPIOH,
	//100
	GPIOH, GPIOH, NULL, GPIOB, GPIOB, GPIOB, GPIOB, GPIOD, GPIOD, GPIOD,
	//110
	GPIOD, GPIOD, GPIOD, NULL, NULL, GPIOD, GPIOD, GPIOJ, GPIOJ, GPIOJ,
	//120
	GPIOJ, GPIOJ, GPIOJ, NULL, NULL, GPIOK, GPIOK, GPIOK, GIOG, GPIOG,
	//130
	GPIOG, GPIOG, GPIOG, GIOG, GPIOG, NULL, NULL, GPIOC, GPIOC, GPIOC,
	//140
	GPIOC, GPIOA, GPIOA, GPIOA, GPIOA, GPIOA, GPIOA, NULL, NULL, NULL,
	//150
	GPIOH, GPIOH, GPIOH, GPIOI, GPIOI, GPIOI, GPIOI, NULL, GPIOA, GPIOA,
	//160
	GPIOC, GPIOC, GPIOC, GPIOD, GPIOD, GPIOD, GPIOD, GPIOD, GPIOD, NULL,
	//170
	NULL, GPIOD, GPIOD, GPIOJ, GPIOJ, GPIOJ, GPIOJ, GPIOG, GPIOG, GPIOG,
	//180
	GPIOG, GPIOG, GPIOG, NULL, NULL, GPIOK, GPIOK, GPIOK, GPIOK, GPIOK,
	//190
	GPIOG, GPIOB, GPIOB, GPIOB, GPIOB, GPIOB, NULL, GPIOB, GPIOB, GPIOE,
	//200
	GPIOE, NULL, NULL, NULL, GPIOI, GPIOI, GPIOI, GPIOI

};


uint16_t pins [208] = {
	//for non-gpio pins, it is set to be 0

	//0
	GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, 0, GPIO_PIN_8, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15,
	//10
	GPIO_PIN_9, GPIO_PIN_10, GPIO_PIN_11, 0, 0, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_12, GPIO_PIN_13,
	//20
	GPIO_PIN_14, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, 0, 0, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_8, GPIO_PIN_9,
	//30
	GPIO_PIN_10, GPIO_PIN_0, GPIO_PIN_1, 0, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3, 0, 0,
	//40
	0, 0, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_3,
	//50
	0, 0, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_4, GPIO_PIN_5, 0, 0,
	//60
	GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_15, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_11,
	//70
	GPIO_PIN_12, 0, 0, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_7, GPIO_PIN_8,
	//80
	GPIO_PIN_9, 0, 0, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_10,
	//90
	GPIO_PIN_11, 0, 0, 0, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_8, GPIO_PIN_9, GPIO_PIN_10,
	//100
	GPIO_PIN_11, GPIO_PIN_12, 0, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_8, GPIO_PIN_9, GPIO_PIN_10,
	//110
	GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, 0, 0, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_8,
	//120
	GPIO_PIN_9, GPIO_PIN_10, GPIO_PIN_11, 0, 0, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_2, GPIO_PIN_3,
	//130
	GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_8, 0, 0, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_8,
	//140
	GPIO_PIN_9, GPIO_PIN_8, GPIO_PIN_9, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, 0, 0, 0,
	//150
	GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3, 0, GPIO_PIN_14, GPIO_PIN_15,
	//160
	GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, 0,
	//170
	0, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_9, GPIO_PIN_10, GPIO_PIN_11,
	//180
	GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, 0, 0, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7,
	//190
	GPIO_PIN_15, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7, 0, GPIO_PIN_8, GPIO_PIN_9, GPIO_PIN_0,
	//200
	GPIO_PIN_1, 0, 0, 0, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7

};




void BHAL_GPIO_WritePin(uint16_t pinNumber,
						GPIO_PinState pinState);
