#include "main.h"
// PIN Defines
B_gpioPin_t GPIO_OUT_0 = {GPIOE, GPIO_PIN_3};
B_gpioPin_t GPIO_OUT_1 = {GPIOI, GPIO_PIN_9};
B_gpioPin_t GPIO_OUT_2 = {GPIOF, GPIO_PIN_2};
B_gpioPin_t GPIO_OUT_3 = {GPIOI, GPIO_PIN_12};
B_gpioPin_t GPIO_OUT_4 = {GPIOI, GPIO_PIN_13};
B_gpioPin_t GPIO_OUT_5 = {GPIOI, GPIO_PIN_14};
B_gpioPin_t GPIO_OUT_6 = {GPIOI, GPIO_PIN_15};
B_gpioPin_t GPIO_OUT_7 = {GPIOG, GPIO_PIN_0};
B_gpioPin_t GPIO_OUT_8 = {GPIOG, GPIO_PIN_1};
// GPIO_OUT_9 WELLOUGHED
B_gpioPin_t GPIO_OUT_10 = {GPIOH, GPIO_PIN_12}; // WELLOUGHED
B_gpioPin_t GPIO_OUT_11 = {GPIOB, GPIO_PIN_13};
B_gpioPin_t GPIO_OUT_12 = {GPIOK, GPIO_PIN_2};
B_gpioPin_t GPIO_OUT_13 = {GPIOG, GPIO_PIN_2};
B_gpioPin_t GPIO_OUT_14 = {GPIOG, GPIO_PIN_3};
B_gpioPin_t GPIO_OUT_15 = {GPIOG, GPIO_PIN_4};
B_gpioPin_t GPIO_OUT_16 = {GPIOG, GPIO_PIN_5};
B_gpioPin_t GPIO_OUT_17 = {GPIOD, GPIO_PIN_3}; // WELLOUGHED
B_gpioPin_t GPIO_OUT_18 = {GPIOJ, GPIO_PIN_12};
B_gpioPin_t GPIO_OUT_19 = {GPIOJ, GPIO_PIN_13};
B_gpioPin_t GPIO_OUT_20 = {GPIOJ, GPIO_PIN_14};
B_gpioPin_t GPIO_OUT_21 = {GPIOJ, GPIO_PIN_15};
B_gpioPin_t GPIO_OUT_22 = {GPIOK, GPIO_PIN_3};
B_gpioPin_t GPIO_OUT_23 = {GPIOK, GPIO_PIN_4};
B_gpioPin_t GPIO_OUT_24 = {GPIOK, GPIO_PIN_5};
B_gpioPin_t GPIO_OUT_25 = {GPIOK, GPIO_PIN_6};
B_gpioPin_t GPIO_OUT_26 = {GPIOK, GPIO_PIN_7};
B_gpioPin_t GPIO_OUT_27 = {GPIOG, GPIO_PIN_15};
B_gpioPin_t GPIO_OUT_28 = {GPIOE, GPIO_PIN_0};
B_gpioPin_t GPIO_OUT_29 = {GPIOI, GPIO_PIN_4}; // FLASH CS
B_gpioPin_t GPIO_OUT_30 = {GPIOI, GPIO_PIN_7}; // FLASH CS

B_gpioPin_t GPIO_EXTI_0 = {GPIOJ, GPIO_PIN_0};
B_gpioPin_t GPIO_EXTI_1 = {GPIOJ, GPIO_PIN_1};
B_gpioPin_t GPIO_EXTI_2 = {GPIOJ, GPIO_PIN_2};
B_gpioPin_t GPIO_EXTI_3 = {GPIOJ, GPIO_PIN_3};
B_gpioPin_t GPIO_EXTI_4 = {GPIOJ, GPIO_PIN_4};
B_gpioPin_t GPIO_EXTI_5 = {GPIOJ, GPIO_PIN_5};
B_gpioPin_t GPIO_EXTI_6 = {GPIOJ, GPIO_PIN_6};
B_gpioPin_t GPIO_EXTI_7 = {GPIOJ, GPIO_PIN_7};
B_gpioPin_t GPIO_EXTI_8 = {GPIOG, GPIO_PIN_8}; // WELLOUGHED
// GPIO_EXTI_9 WELLOUGHED
B_gpioPin_t GPIO_EXTI_10 = {GPIOD, GPIO_PIN_10};
B_gpioPin_t GPIO_EXTI_11 = {GPIOE, GPIO_PIN_11};
B_gpioPin_t GPIO_EXTI_12 = {GPIOE, GPIO_PIN_12};
B_gpioPin_t GPIO_EXTI_13 = {GPIOE, GPIO_PIN_13};
B_gpioPin_t GPIO_EXTI_15 = {GPIOE, GPIO_PIN_15};
